// web/src/routes/verify-email/+page.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
</script>

<div class="flex min-h-screen items-center justify-center bg-neutral-50">
	<Card.Root class="w-full max-w-sm">
		<Card.Header class="items-center text-center">
			<div class="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-xl bg-neutral-900">
				<Icon icon="ph:envelope-duotone" class="h-6 w-6 text-white" />
			</div>
			<Card.Title class="text-2xl">Check your email</Card.Title>
			<Card.Description>
				We sent a verification link to your email address. Click the link to verify your account.
			</Card.Description>
		</Card.Header>

		<Card.Content class="text-center">
			<p class="text-sm text-neutral-400">
				Didn't receive it? Check your spam folder or
				<a href="/signup" class="font-medium text-neutral-700 hover:text-neutral-900">
					try signing up again</a
				>.
			</p>
		</Card.Content>

		<Card.Footer class="justify-center">
			<Button variant="ghost" href="/login" class="gap-2">
				<Icon icon="ph:arrow-left" class="h-4 w-4" />
				Back to login
			</Button>
		</Card.Footer>
	</Card.Root>
</div>

// web-react/src/routes/verify-email.tsx
import { createFileRoute } from '@tanstack/react-router';
import { Mail } from 'lucide-react';

export const Route = createFileRoute('/verify-email')({
	component: VerifyEmailPage,
});

function VerifyEmailPage() {
	return (
		<div className="flex min-h-screen items-center justify-center bg-stone-100">
			<div className="w-full max-w-md space-y-6 rounded-xl bg-white p-8 text-center shadow-sm">
				<div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-violet-100">
					<Mail className="h-8 w-8 text-violet-600" />
				</div>
				<h1 className="text-2xl font-bold text-stone-900">Check your email</h1>
				<p className="text-stone-600">
					We&apos;ve sent you a verification link. Click the link in the email to verify
					your account and get started.
				</p>
				<p className="text-sm text-stone-400">
					The link expires in 1 hour. Didn&apos;t receive it? Check your spam folder.
				</p>
				<a
					href="/login"
					className="inline-block text-sm font-medium text-violet-600 hover:text-violet-500"
				>
					Back to login
				</a>
			</div>
		</div>
	);
}
