// web/src/routes/dashboard/devices/+page.svelte
<script lang="ts">
	import { listDevices } from '$lib/api/devices.remote';
	import { getConfig } from '$lib/api/settings.remote';
	import { createPairingCode, getPairingStatus } from '$lib/api/pairing.remote';
	import { dashboardWs } from '$lib/stores/dashboard-ws.svelte';
	import { onMount } from 'svelte';
	import DeviceCard from '$lib/components/DeviceCard.svelte';
	import Icon from '@iconify/svelte';
	import { toast } from '$lib/toast';

	interface DeviceEntry {
		deviceId: string;
		name: string;
		status: 'online' | 'offline';
		model: string | null;
		manufacturer: string | null;
		androidVersion: string | null;
		screenWidth: number | null;
		screenHeight: number | null;
		batteryLevel: number | null;
		isCharging: boolean;
		lastSeen: string;
		lastGoal: { goal: string; status: string; startedAt: string } | null;
	}

	const [initialDevices, llmConfig] = await Promise.all([listDevices(), getConfig()]);
	const hasLlmConfig = llmConfig !== null;

	let devices = $state<DeviceEntry[]>(
		initialDevices.map((d) => ({
			deviceId: d.deviceId,
			name: d.name,
			status: d.status as 'online' | 'offline',
			model: d.model as string | null,
			manufacturer: d.manufacturer as string | null,
			androidVersion: d.androidVersion as string | null,
			screenWidth: d.screenWidth as number | null,
			screenHeight: d.screenHeight as number | null,
			batteryLevel: d.batteryLevel as number | null,
			isCharging: d.isCharging as boolean,
			lastSeen: d.lastSeen,
			lastGoal: d.lastGoal as DeviceEntry['lastGoal']
		}))
	);

	// ─── Pairing modal state ───────────────────────────────────
	type ModalState = 'closed' | 'loading' | 'code' | 'expired' | 'paired';
	let modalState = $state<ModalState>('closed');
	let pairingCode = $state('');
	let expiresAt = $state('');
	let secondsLeft = $state(0);
	let countdownTimer: ReturnType<typeof setInterval> | null = null;
	let pollTimer: ReturnType<typeof setInterval> | null = null;

	function clearTimers() {
		if (countdownTimer) {
			clearInterval(countdownTimer);
			countdownTimer = null;
		}
		if (pollTimer) {
			clearInterval(pollTimer);
			pollTimer = null;
		}
	}

	function closeModal() {
		clearTimers();
		modalState = 'closed';
		pairingCode = '';
		expiresAt = '';
		secondsLeft = 0;
	}

	function startCountdown() {
		const updateCountdown = () => {
			const now = Date.now();
			const expires = new Date(expiresAt).getTime();
			const remaining = Math.max(0, Math.floor((expires - now) / 1000));
			secondsLeft = remaining;
			if (remaining <= 0) {
				clearTimers();
				modalState = 'expired';
			}
		};
		updateCountdown();
		countdownTimer = setInterval(updateCountdown, 1000);
	}

	function startPolling() {
		pollTimer = setInterval(async () => {
			try {
				const status = await getPairingStatus();
				if (status.paired) {
					clearTimers();
					modalState = 'paired';
					// Refresh devices list
					const refreshed = await listDevices();
					devices = refreshed.map((d) => ({
						deviceId: d.deviceId,
						name: d.name,
						status: d.status as 'online' | 'offline',
						model: d.model as string | null,
						manufacturer: d.manufacturer as string | null,
						androidVersion: d.androidVersion as string | null,
						screenWidth: d.screenWidth as number | null,
						screenHeight: d.screenHeight as number | null,
						batteryLevel: d.batteryLevel as number | null,
						isCharging: d.isCharging as boolean,
						lastSeen: d.lastSeen,
						lastGoal: d.lastGoal as DeviceEntry['lastGoal']
					}));
				} else if (status.expired) {
					clearTimers();
					modalState = 'expired';
				}
			} catch {
				// Silently ignore polling errors
			}
		}, 2000);
	}

	async function generateCode() {
		modalState = 'loading';
		try {
			const result = await createPairingCode();
			pairingCode = result.code;
			expiresAt = result.expiresAt;
			modalState = 'code';
			startCountdown();
			startPolling();
		} catch (e: any) {
			toast.error(e.message ?? 'Failed to generate pairing code');
			closeModal();
		}
	}

	async function openPairingModal() {
		await generateCode();
	}

	async function regenerateCode() {
		clearTimers();
		await generateCode();
	}

	function formatTime(seconds: number): string {
		const m = Math.floor(seconds / 60);
		const s = seconds % 60;
		return `${m}:${s.toString().padStart(2, '0')}`;
	}

	// ─── WebSocket subscriptions ───────────────────────────────
	onMount(() => {
		// Auto-open pairing modal if ?pair query param is present
		const params = new URLSearchParams(window.location.search);
		if (params.has('pair')) {
			openPairingModal();
			// Clean up the URL
			history.replaceState({}, '', window.location.pathname);
		}

		const unsub = dashboardWs.subscribe((msg) => {
			if (msg.type === 'device_online') {
				const id = msg.deviceId as string;
				const name = msg.name as string;
				const existing = devices.find((d) => d.deviceId === id);
				if (existing) {
					existing.status = 'online';
					existing.lastSeen = new Date().toISOString();
					devices = [...devices];
				} else {
					devices = [
						{
							deviceId: id,
							name,
							status: 'online',
							model: null,
							manufacturer: null,
							androidVersion: null,
							screenWidth: null,
							screenHeight: null,
							batteryLevel: null,
							isCharging: false,
							lastSeen: new Date().toISOString(),
							lastGoal: null
						},
						...devices
					];
				}
				toast.success(`${name} connected`);
			} else if (msg.type === 'device_offline') {
				const id = msg.deviceId as string;
				const existing = devices.find((d) => d.deviceId === id);
				if (existing) {
					existing.status = 'offline';
					devices = [...devices];
					toast.info(`${existing.name} disconnected`);
				}
			} else if (msg.type === 'device_status') {
				const id = msg.deviceId as string;
				const existing = devices.find((d) => d.deviceId === id);
				if (existing) {
					existing.batteryLevel = msg.batteryLevel as number;
					existing.isCharging = msg.isCharging as boolean;
					devices = [...devices];
				}
			}
		});
		return () => {
			unsub();
			clearTimers();
		};
	});
</script>

<!-- Page header -->
<div class="mb-6 flex items-center justify-between">
	<h2 class="text-xl md:text-2xl font-bold">Devices</h2>
	<div class="flex items-center gap-2">
		<a
			href="https://github.com/unitedbyai/droidclaw/releases/download/v0.5.3/app-debug.apk"
			class="inline-flex items-center gap-1.5 rounded-lg border border-stone-200 px-4 py-2 text-sm font-medium text-stone-600 hover:bg-stone-50"
		>
			<Icon icon="solar:download-bold-duotone" class="h-4 w-4" />
			Download APK
		</a>
		<button
			onclick={openPairingModal}
			class="inline-flex items-center gap-1.5 rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white transition-transform hover:bg-stone-800 active:scale-[0.98]"
		>
			<Icon icon="solar:link-round-bold-duotone" class="h-4 w-4" />
			Pair Device
		</button>
	</div>
</div>

<!-- LLM not configured banner -->
{#if !hasLlmConfig && devices.length > 0}
	<a
		href="/dashboard/settings"
		class="mb-6 flex items-center gap-3 rounded-2xl bg-amber-50 p-4 transition-colors hover:bg-amber-100/80"
	>
		<div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-amber-100">
			<Icon icon="solar:danger-triangle-bold-duotone" class="h-5 w-5 text-amber-600" />
		</div>
		<div class="flex-1">
			<p class="text-sm font-semibold text-amber-900">Set up your LLM provider</p>
			<p class="mt-0.5 text-xs text-amber-700">Your device is paired but needs an AI model configured to run tasks.</p>
		</div>
		<Icon icon="solar:alt-arrow-right-linear" class="h-5 w-5 text-amber-400" />
	</a>
{/if}

{#if devices.length === 0}
	<div class="rounded-2xl bg-white p-6 md:p-10 text-center">
		<div class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-stone-100">
			<Icon icon="solar:smartphone-bold-duotone" class="h-6 w-6 text-stone-400" />
		</div>
		<p class="font-medium text-stone-600">No devices connected</p>
		<p class="mt-1 text-sm text-stone-400">
			Install the Android app and pair your device to get started.
		</p>
		<button
			onclick={openPairingModal}
			class="mt-5 inline-flex items-center gap-1.5 rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white transition-transform hover:bg-stone-800 active:scale-[0.98]"
		>
			<Icon icon="solar:link-round-bold-duotone" class="h-4 w-4" />
			Pair Device
		</button>
	</div>
{:else}
	<div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
		{#each devices as d (d.deviceId)}
			<DeviceCard {...d} />
		{/each}
	</div>
{/if}

<!-- Pairing Modal -->
{#if modalState !== 'closed'}
	<!-- Backdrop -->
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
		onkeydown={(e) => { if (e.key === 'Escape') closeModal(); }}
		onclick={(e) => { if (e.target === e.currentTarget) closeModal(); }}
	>
		<!-- Modal -->
		<div class="relative w-full max-w-md rounded-2xl bg-white shadow-xl">
			<!-- Header -->
			<div class="flex items-center justify-between border-b border-stone-100 px-6 py-4">
				<h3 class="text-lg font-semibold text-stone-900">Pair Your Device</h3>
				<button
					onclick={closeModal}
					class="flex h-8 w-8 items-center justify-center rounded-lg text-stone-400 hover:bg-stone-100 hover:text-stone-600"
				>
					<Icon icon="solar:close-circle-bold-duotone" class="h-5 w-5" />
				</button>
			</div>

			<!-- Body -->
			<div class="px-6 py-8">
				{#if modalState === 'loading'}
					<!-- Loading state -->
					<div class="flex flex-col items-center gap-3">
						<Icon icon="solar:refresh-circle-bold-duotone" class="h-8 w-8 animate-spin text-stone-400" />
						<p class="text-sm text-stone-500">Generating pairing code...</p>
					</div>
				{:else if modalState === 'code'}
					<!-- Code display state -->
					<div class="flex flex-col items-center">
						<p class="mb-6 text-center text-sm text-stone-500">
							Open DroidClaw on your Android device and enter this code:
						</p>

						<!-- OTP digits -->
						<div class="mb-5 flex gap-2">
							{#each pairingCode.split('') as digit}
								<div class="flex h-14 w-11 items-center justify-center rounded-xl border-2 border-stone-200 bg-stone-50">
									<span class="font-mono text-2xl font-bold text-stone-900">{digit}</span>
								</div>
							{/each}
						</div>

						<!-- Countdown -->
						<p class="mb-2 text-sm text-stone-400">
							Expires in {formatTime(secondsLeft)}
						</p>

						<!-- Copy code button -->
						<button
							onclick={() => {
								navigator.clipboard.writeText(pairingCode);
								toast.success('Code copied to clipboard');
							}}
							class="mb-4 inline-flex items-center gap-1.5 rounded-lg border border-stone-200 px-3 py-1.5 text-sm text-stone-600 transition-all hover:bg-stone-50 active:scale-[0.98]"
						>
							<Icon icon="solar:copy-bold-duotone" class="h-4 w-4" />
							Copy code
						</button>

						<!-- Waiting indicator -->
						<div class="flex items-center gap-2 text-sm text-stone-500">
							<Icon icon="solar:refresh-circle-bold-duotone" class="h-4 w-4 animate-spin" />
							Waiting for device...
						</div>
					</div>
				{:else if modalState === 'expired'}
					<!-- Expired state -->
					<div class="flex flex-col items-center gap-4">
						<div class="flex h-12 w-12 items-center justify-center rounded-full bg-stone-100">
							<Icon icon="solar:clock-circle-bold-duotone" class="h-6 w-6 text-stone-400" />
						</div>
						<p class="font-medium text-stone-600">Code expired</p>
						<button
							onclick={regenerateCode}
							class="inline-flex items-center gap-1.5 rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white transition-transform hover:bg-stone-800 active:scale-[0.98]"
						>
							<Icon icon="solar:refresh-bold-duotone" class="h-4 w-4" />
							Generate new code
						</button>
					</div>
				{:else if modalState === 'paired'}
					<!-- Success state -->
					<div class="flex flex-col items-center gap-4">
						<div class="flex h-12 w-12 items-center justify-center rounded-full bg-green-100">
							<Icon icon="solar:check-circle-bold-duotone" class="h-6 w-6 text-green-600" />
						</div>
						<p class="text-lg font-semibold text-stone-900">Device Paired!</p>
						<p class="text-sm text-stone-500">Your device is now connected and ready to use.</p>
						<button
							onclick={closeModal}
							class="inline-flex items-center gap-1.5 rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white transition-transform hover:bg-stone-800 active:scale-[0.98]"
						>
							Done
						</button>
					</div>
				{/if}
			</div>

			<!-- Footer (shown only during code/expired states) -->
			{#if modalState === 'code' || modalState === 'expired'}
				<div class="border-t border-stone-100 px-6 py-4">
					<a
						href="/dashboard/api-keys"
						class="flex items-center justify-center gap-1.5 text-sm text-stone-400 hover:text-stone-600"
					>
						<Icon icon="solar:key-bold-duotone" class="h-3.5 w-3.5" />
						Developer? Use API keys for manual setup
					</a>
				</div>
			{/if}
		</div>
	</div>
{/if}

// web-react/src/routes/_auth/dashboard/devices/index.tsx
import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { useState, useEffect, useCallback } from 'react';
import {
	Smartphone,
	Wifi,
	WifiOff,
	Plus,
	Battery,
	X,
	Copy,
	CheckCircle2,
} from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { track } from '@/lib/analytics/track';
import { DEVICE_CARD_CLICK } from '@/lib/analytics/events';

export const Route = createFileRoute('/_auth/dashboard/devices/')({
	component: DevicesPage,
});

function DevicesPage() {
	const queryClient = useQueryClient();
	const [showPairing, setShowPairing] = useState(false);

	const { data: devices, isLoading } = useQuery({
		queryKey: ['devices'],
		queryFn: () => api.listDevices(),
		refetchInterval: 10000,
	});

	return (
		<div className="mx-auto max-w-5xl space-y-6">
			{/* Header */}
			<div className="flex items-center justify-between">
				<div>
					<h1 className="text-2xl font-bold text-stone-900">Devices</h1>
					<p className="mt-1 text-sm text-stone-500">
						Manage your connected Android devices
					</p>
				</div>
				<button
					onClick={() => setShowPairing(true)}
					className="flex items-center gap-2 rounded-lg bg-stone-900 px-4 py-2.5 text-sm font-medium text-white hover:bg-stone-800"
				>
					<Plus className="h-4 w-4" />
					Pair device
				</button>
			</div>

			{/* Device grid */}
			{isLoading ? (
				<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
					{[1, 2, 3].map((i) => (
						<div
							key={i}
							className="h-40 animate-pulse rounded-xl border border-stone-200 bg-white"
						/>
					))}
				</div>
			) : devices && devices.length > 0 ? (
				<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
					{devices.map((device) => {
						const isOnline = device.status === 'online';
						return (
							<Link
								key={device.deviceId}
								to="/dashboard/devices/$deviceId"
								params={{ deviceId: device.deviceId }}
								onClick={() => track(DEVICE_CARD_CLICK)}
								className="group rounded-xl border border-stone-200 bg-white p-5 transition-shadow hover:shadow-md"
							>
								<div className="flex items-start justify-between">
									<div
										className={`flex h-10 w-10 items-center justify-center rounded-lg ${
											isOnline ? 'bg-emerald-50' : 'bg-stone-100'
										}`}
									>
										<Smartphone
											className={`h-5 w-5 ${isOnline ? 'text-emerald-600' : 'text-stone-400'}`}
										/>
									</div>
									<div className="flex items-center gap-1.5">
										{isOnline ? (
											<>
												<Wifi className="h-3.5 w-3.5 text-emerald-500" />
												<span className="text-xs font-medium text-emerald-600">
													Online
												</span>
											</>
										) : (
											<>
												<WifiOff className="h-3.5 w-3.5 text-stone-300" />
												<span className="text-xs text-stone-400">Offline</span>
											</>
										)}
									</div>
								</div>

								<div className="mt-3">
									<h3 className="text-sm font-semibold text-stone-900 group-hover:text-violet-700">
										{device.name}
									</h3>
									<p className="mt-0.5 text-xs text-stone-500">
										{device.model || 'Unknown model'}
									</p>
								</div>

								<div className="mt-3 flex items-center gap-4 text-xs text-stone-400">
									{device.batteryLevel !== null && (
										<span className="flex items-center gap-1">
											<Battery className="h-3 w-3" />
											{device.batteryLevel}%
										</span>
									)}
									{device.androidVersion && (
										<span>Android {device.androidVersion}</span>
									)}
								</div>

								{!isOnline && (
									<p className="mt-2 text-xs text-stone-400">
										Last seen{' '}
										{formatDistanceToNow(new Date(device.lastSeen), {
											addSuffix: true,
										})}
									</p>
								)}

								{device.lastGoal && (
									<div className="mt-3 border-t border-stone-100 pt-2">
										<p className="truncate text-xs text-stone-500">
											<span
												className={`mr-1.5 inline-block h-1.5 w-1.5 rounded-full ${
													device.lastGoal.status === 'completed'
														? 'bg-emerald-500'
														: device.lastGoal.status === 'running'
															? 'bg-violet-500'
															: 'bg-red-400'
												}`}
											/>
											{device.lastGoal.goal}
										</p>
									</div>
								)}
							</Link>
						);
					})}
				</div>
			) : (
				<div className="rounded-xl border border-stone-200 bg-white p-12 text-center">
					<Smartphone className="mx-auto h-10 w-10 text-stone-300" />
					<h3 className="mt-3 text-sm font-semibold text-stone-900">
						No devices paired
					</h3>
					<p className="mt-1 text-sm text-stone-500">
						Pair your first Android device to get started
					</p>
					<button
						onClick={() => setShowPairing(true)}
						className="mt-4 inline-flex items-center gap-2 rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white hover:bg-stone-800"
					>
						<Plus className="h-4 w-4" />
						Pair device
					</button>
				</div>
			)}

			{/* Pairing dialog */}
			{showPairing && (
				<PairingDialog
					onClose={() => {
						setShowPairing(false);
						queryClient.invalidateQueries({ queryKey: ['devices'] });
					}}
				/>
			)}
		</div>
	);
}

function PairingDialog({ onClose }: { onClose: () => void }) {
	const [copied, setCopied] = useState(false);
	const [secondsLeft, setSecondsLeft] = useState<number | null>(null);

	const { data: pairing, mutate: createCode, isPending } = useMutation({
		mutationFn: () => api.createPairingCode(),
		onSuccess: (data) => {
			const expires = new Date(data.expiresAt).getTime();
			setSecondsLeft(Math.max(0, Math.floor((expires - Date.now()) / 1000)));
		},
	});

	// Generate code on mount
	useEffect(() => {
		createCode();
	}, [createCode]);

	// Countdown timer
	useEffect(() => {
		if (secondsLeft === null || secondsLeft <= 0) return;
		const timer = setInterval(() => {
			setSecondsLeft((prev) => {
				if (prev === null || prev <= 1) {
					clearInterval(timer);
					return 0;
				}
				return prev - 1;
			});
		}, 1000);
		return () => clearInterval(timer);
	}, [secondsLeft]);

	// Poll pairing status
	const { data: status } = useQuery({
		queryKey: ['pairingStatus'],
		queryFn: () => api.getPairingStatus(),
		refetchInterval: 3000,
		enabled: !!pairing?.code && (secondsLeft ?? 0) > 0,
	});

	const handleCopy = useCallback(() => {
		if (pairing?.code) {
			navigator.clipboard.writeText(pairing.code);
			setCopied(true);
			setTimeout(() => setCopied(false), 2000);
		}
	}, [pairing?.code]);

	const isPaired = status?.paired === true;

	return (
		<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
			<div className="relative w-full max-w-md rounded-xl bg-white p-6 shadow-xl">
				<button
					onClick={onClose}
					className="absolute right-4 top-4 rounded p-1 text-stone-400 hover:text-stone-600"
				>
					<X className="h-5 w-5" />
				</button>

				<h2 className="text-lg font-bold text-stone-900">Pair a device</h2>
				<p className="mt-1 text-sm text-stone-500">
					Enter this code in the DroidClaw Android app to pair your device.
				</p>

				{isPaired ? (
					<div className="mt-6 text-center">
						<CheckCircle2 className="mx-auto h-12 w-12 text-emerald-500" />
						<p className="mt-3 text-sm font-semibold text-emerald-700">
							Device paired successfully!
						</p>
						<button
							onClick={onClose}
							className="mt-4 rounded-lg bg-stone-900 px-6 py-2 text-sm font-medium text-white hover:bg-stone-800"
						>
							Done
						</button>
					</div>
				) : isPending ? (
					<div className="mt-6 flex justify-center">
						<div className="h-8 w-8 animate-spin rounded-full border-2 border-stone-200 border-t-stone-600" />
					</div>
				) : pairing?.code ? (
					<div className="mt-6 space-y-4">
						{/* Code display */}
						<div className="flex items-center justify-center gap-3 rounded-lg bg-stone-50 px-4 py-6">
							<span className="font-mono text-3xl font-bold tracking-[0.3em] text-stone-900">
								{pairing.code}
							</span>
							<button
								onClick={handleCopy}
								className="rounded p-1.5 text-stone-400 hover:text-stone-600"
								title="Copy code"
							>
								{copied ? (
									<CheckCircle2 className="h-5 w-5 text-emerald-500" />
								) : (
									<Copy className="h-5 w-5" />
								)}
							</button>
						</div>

						{/* Timer */}
						{secondsLeft !== null && secondsLeft > 0 ? (
							<p className="text-center text-xs text-stone-400">
								Code expires in{' '}
								<span className="font-medium">
									{Math.floor(secondsLeft / 60)}:
									{String(secondsLeft % 60).padStart(2, '0')}
								</span>
							</p>
						) : (
							<div className="text-center">
								<p className="text-xs text-red-500">Code expired</p>
								<button
									onClick={() => createCode()}
									className="mt-2 text-sm font-medium text-violet-600 hover:text-violet-700"
								>
									Generate new code
								</button>
							</div>
						)}
					</div>
				) : null}
			</div>
		</div>
	);
}
