// web/src/routes/dashboard/+page.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { DASHBOARD_CARD_CLICK } from '$lib/analytics/events';
	import { getConfig } from '$lib/api/settings.remote';
	import { listDevices } from '$lib/api/devices.remote';
	import * as Card from '$lib/components/ui/card';
	import { Progress } from '$lib/components/ui/progress';
	import { Badge } from '$lib/components/ui/badge';

	let { data } = $props();

	const cards = [
		{
			href: '/dashboard/devices',
			icon: 'solar:smartphone-bold-duotone',
			title: 'Devices',
			desc: 'Manage connected phones',
			color: 'bg-emerald-100 text-emerald-600'
		},
		{
			href: '/dashboard/api-keys',
			icon: 'solar:key-bold-duotone',
			title: 'API Keys',
			desc: 'Create keys for your devices',
			color: 'bg-amber-100 text-amber-600'
		},
		{
			href: '/dashboard/settings',
			icon: 'solar:settings-bold-duotone',
			title: 'Settings',
			desc: 'Configure LLM provider',
			color: 'bg-violet-100 text-violet-600'
		}
	];

	// Setup checklist data
	const [config, devices] = await Promise.all([getConfig(), listDevices()]);
	const hasConfig = config !== null;
	const hasDevice = (devices as unknown[]).length > 0;

	const checklist = [
		{
			label: 'Configure LLM provider',
			desc: 'Choose your AI model and add credentials',
			href: '/dashboard/settings',
			done: hasConfig
		},
		{
			label: 'Install the Android app',
			desc: 'Download and install DroidClaw on your phone',
			href: 'https://github.com/unitedbyai/droidclaw/releases/latest',
			done: hasDevice
		},
		{
			label: 'Connect your device',
			desc: 'Pair your phone with the dashboard',
			href: '/dashboard/devices?pair',
			done: hasDevice
		}
	];

	const completedCount = checklist.filter((s) => s.done).length;
	const allComplete = completedCount === checklist.length;
	const progressPercent = (completedCount / checklist.length) * 100;
</script>

<h2 class="mb-1 text-xl font-bold md:text-2xl">Dashboard</h2>
<p class="mb-8 text-stone-500">Welcome back, {data.user.name}.</p>

{#if data.plan}
	<Card.Root class="mb-8">
		<Card.Content class="flex items-center gap-4 py-4">
			<div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-100">
				<Icon icon="solar:verified-check-bold-duotone" class="h-5 w-5 text-emerald-600" />
			</div>
			<div>
				<Card.Title class="text-sm">
					{data.plan === 'ltd' ? 'Lifetime Deal' : data.plan} Plan
				</Card.Title>
				<Card.Description>
					License: {data.licenseKey ?? 'Active'}
				</Card.Description>
			</div>
			<Badge variant="outline" class="ml-auto border-emerald-200 bg-emerald-50 text-emerald-700">
				Active
			</Badge>
		</Card.Content>
	</Card.Root>
{/if}

{#if !allComplete}
	<div class="mb-6">
		<div class="mb-3 flex items-center gap-3">
			<p class="text-sm font-medium text-stone-500">{completedCount} of {checklist.length} complete</p>
			<Progress value={progressPercent} class="h-1.5 max-w-[120px]" />
		</div>
		<Card.Root>
			{#each checklist as step, i}
				<a
					href={step.href}
					class="flex items-center gap-4 p-5 transition-colors hover:bg-stone-50/80
						{i > 0 ? 'border-t border-stone-100' : ''}
						{i === 0 ? 'rounded-t-2xl' : ''}
						{i === checklist.length - 1 ? 'rounded-b-2xl' : ''}"
				>
					<div class="flex h-8 w-8 shrink-0 items-center justify-center">
						{#if step.done}
							<Icon icon="solar:check-circle-bold" class="h-6 w-6 text-emerald-500" />
						{:else}
							<Icon icon="solar:circle-linear" class="h-6 w-6 text-stone-300" />
						{/if}
					</div>
					<div class="flex-1">
						<h3 class="text-sm font-semibold {step.done ? 'text-stone-400 line-through' : 'text-stone-900'}">{step.label}</h3>
						<p class="mt-0.5 text-xs text-stone-400">{step.desc}</p>
					</div>
					<Icon icon="solar:alt-arrow-right-linear" class="h-4 w-4 text-stone-300" />
				</a>
			{/each}
		</Card.Root>
	</div>
{/if}

<Card.Root>
	{#each cards as card, i}
		<a
			href={card.href}
			data-umami-event={DASHBOARD_CARD_CLICK}
			data-umami-event-section={card.title.toLowerCase().replace(' ', '-')}
			class="flex items-center gap-4 p-5 transition-all duration-200 hover:bg-stone-50/80
				{i > 0 ? 'border-t border-stone-100' : ''}
				{i === 0 ? 'rounded-t-2xl' : ''}
				{i === cards.length - 1 ? 'rounded-b-2xl' : ''}"
		>
			<div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full {card.color}">
				<Icon icon={card.icon} class="h-5 w-5" />
			</div>
			<div class="flex-1">
				<h3 class="font-semibold text-stone-900">{card.title}</h3>
				<p class="mt-0.5 text-sm text-stone-500">{card.desc}</p>
			</div>
			<Icon icon="solar:alt-arrow-right-linear" class="h-4 w-4 text-stone-300" />
		</a>
	{/each}
</Card.Root>

// web-react/src/routes/_auth/dashboard/index.tsx
import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import {
	Smartphone,
	Key,
	Settings,
	Wifi,
	WifiOff,
	CheckCircle2,
	ArrowRight,
	Zap,
} from 'lucide-react';
import { track } from '@/lib/analytics/track';
import { DASHBOARD_CARD_CLICK } from '@/lib/analytics/events';

export const Route = createFileRoute('/_auth/dashboard/')({
	component: DashboardPage,
});

function DashboardPage() {
	const { data: devices, isLoading } = useQuery({
		queryKey: ['devices'],
		queryFn: () => api.listDevices(),
	});

	const { data: config } = useQuery({
		queryKey: ['config'],
		queryFn: () => api.getConfig(),
	});

	const { data: apiKeys } = useQuery({
		queryKey: ['apiKeys'],
		queryFn: () => api.listApiKeys(),
	});

	const onlineDevices = devices?.filter((d) => d.status === 'online') ?? [];
	const hasDevices = (devices?.length ?? 0) > 0;
	const hasConfig = !!config;
	const hasApiKeys = (apiKeys?.length ?? 0) > 0;

	return (
		<div className="mx-auto max-w-5xl space-y-8">
			{/* Page header */}
			<div>
				<h1 className="text-2xl font-bold text-stone-900">Dashboard</h1>
				<p className="mt-1 text-sm text-stone-500">
					Overview of your DroidClaw setup
				</p>
			</div>

			{/* Setup checklist */}
			{(!hasDevices || !hasConfig || !hasApiKeys) && (
				<div className="rounded-xl border border-amber-200 bg-amber-50 p-6">
					<h2 className="flex items-center gap-2 text-sm font-semibold text-amber-900">
						<Zap className="h-4 w-4" />
						Getting started
					</h2>
					<div className="mt-4 space-y-3">
						<ChecklistItem
							done={hasConfig}
							label="Configure LLM provider"
							to="/dashboard/settings"
						/>
						<ChecklistItem
							done={hasApiKeys}
							label="Create an API key"
							to="/dashboard/api-keys"
						/>
						<ChecklistItem
							done={hasDevices}
							label="Pair a device"
							to="/dashboard/devices"
						/>
					</div>
				</div>
			)}

			{/* Stat cards */}
			<div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
				<StatCard
					label="Total devices"
					value={isLoading ? '...' : String(devices?.length ?? 0)}
					icon={<Smartphone className="h-5 w-5 text-stone-400" />}
				/>
				<StatCard
					label="Online now"
					value={isLoading ? '...' : String(onlineDevices.length)}
					icon={<Wifi className="h-5 w-5 text-emerald-500" />}
				/>
				<StatCard
					label="API keys"
					value={String(apiKeys?.length ?? 0)}
					icon={<Key className="h-5 w-5 text-stone-400" />}
				/>
			</div>

			{/* Quick nav cards */}
			<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
				<NavCard
					to="/dashboard/devices"
					title="Devices"
					description="View and manage your connected Android devices"
					icon={<Smartphone className="h-6 w-6 text-violet-600" />}
				/>
				<NavCard
					to="/dashboard/api-keys"
					title="API Keys"
					description="Create and manage authentication keys"
					icon={<Key className="h-6 w-6 text-violet-600" />}
				/>
				<NavCard
					to="/dashboard/settings"
					title="Settings"
					description="Configure your LLM provider and preferences"
					icon={<Settings className="h-6 w-6 text-violet-600" />}
				/>
			</div>

			{/* Devices quick list */}
			{hasDevices && (
				<div className="rounded-xl border border-stone-200 bg-white p-6">
					<div className="flex items-center justify-between">
						<h2 className="text-sm font-semibold text-stone-900">Devices</h2>
						<Link
							to="/dashboard/devices"
							className="flex items-center gap-1 text-xs text-violet-600 hover:text-violet-700"
						>
							View all <ArrowRight className="h-3 w-3" />
						</Link>
					</div>
					<div className="mt-4 space-y-2">
						{devices?.slice(0, 5).map((device) => (
							<Link
								key={device.deviceId}
								to="/dashboard/devices/$deviceId"
								params={{ deviceId: device.deviceId }}
								className="flex items-center justify-between rounded-lg bg-stone-50 px-3 py-2 hover:bg-stone-100"
							>
								<div className="flex items-center gap-3">
									{device.status === 'online' ? (
										<Wifi className="h-4 w-4 text-emerald-500" />
									) : (
										<WifiOff className="h-4 w-4 text-stone-300" />
									)}
									<span className="text-sm font-medium text-stone-700">
										{device.name}
									</span>
								</div>
								<span className="text-xs text-stone-400">
									{device.model || 'Unknown'}
								</span>
							</Link>
						))}
					</div>
				</div>
			)}
		</div>
	);
}

function ChecklistItem({
	done,
	label,
	to,
}: {
	done: boolean;
	label: string;
	to: string;
}) {
	return (
		<Link
			to={to}
			className="flex items-center gap-3 rounded-lg px-2 py-1 hover:bg-amber-100"
		>
			<CheckCircle2
				className={`h-4 w-4 ${done ? 'text-emerald-500' : 'text-stone-300'}`}
			/>
			<span
				className={`text-sm ${done ? 'text-stone-500 line-through' : 'font-medium text-stone-700'}`}
			>
				{label}
			</span>
		</Link>
	);
}

function StatCard({
	label,
	value,
	icon,
}: {
	label: string;
	value: string;
	icon: React.ReactNode;
}) {
	return (
		<div className="rounded-xl border border-stone-200 bg-white p-5">
			<div className="flex items-center justify-between">
				<p className="text-sm text-stone-500">{label}</p>
				{icon}
			</div>
			<p className="mt-2 text-2xl font-bold text-stone-900">{value}</p>
		</div>
	);
}

function NavCard({
	to,
	title,
	description,
	icon,
}: {
	to: string;
	title: string;
	description: string;
	icon: React.ReactNode;
}) {
	return (
		<Link
			to={to}
			onClick={() => track(DASHBOARD_CARD_CLICK, { card: title })}
			className="group rounded-xl border border-stone-200 bg-white p-5 transition-shadow hover:shadow-md"
		>
			<div className="flex items-start gap-3">
				<div className="rounded-lg bg-violet-50 p-2">{icon}</div>
				<div>
					<h3 className="text-sm font-semibold text-stone-900 group-hover:text-violet-700">
						{title}
					</h3>
					<p className="mt-1 text-xs text-stone-500">{description}</p>
				</div>
			</div>
		</Link>
	);
}
