// web-react/src/routes/_auth/dashboard/activate.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useMutation } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { useState, useEffect } from 'react';
import { KeyRound, CheckCircle2, AlertCircle } from 'lucide-react';
import { track } from '@/lib/analytics/track';
import {
	LICENSE_ACTIVATE_MANUAL,
	LICENSE_ACTIVATE_CHECKOUT,
	LICENSE_PURCHASE_CLICK,
} from '@/lib/analytics/events';

export const Route = createFileRoute('/_auth/dashboard/activate')({
	component: ActivatePage,
});

function ActivatePage() {
	const navigate = useNavigate();
	const [licenseKey, setLicenseKey] = useState('');
	const search = Route.useSearch() as { checkout_id?: string };

	// Auto-activate from checkout redirect
	const activateCheckout = useMutation({
		mutationFn: (checkoutId: string) => api.activateFromCheckout(checkoutId),
		onSuccess: () => {
			track(LICENSE_ACTIVATE_CHECKOUT);
		},
	});

	useEffect(() => {
		if (search.checkout_id) {
			activateCheckout.mutate(search.checkout_id);
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [search.checkout_id]);

	// Manual key activation
	const activateKey = useMutation({
		mutationFn: () => api.activateLicense(licenseKey.trim()),
		onSuccess: () => {
			track(LICENSE_ACTIVATE_MANUAL);
		},
	});

	const isActivated = activateKey.isSuccess || activateCheckout.isSuccess;
	const error = activateKey.error || activateCheckout.error;

	return (
		<div className="flex min-h-[60vh] items-center justify-center">
			<div className="w-full max-w-md space-y-6 rounded-xl border border-stone-200 bg-white p-8">
				{isActivated ? (
					<div className="text-center">
						<CheckCircle2 className="mx-auto h-12 w-12 text-emerald-500" />
						<h1 className="mt-4 text-xl font-bold text-stone-900">
							License activated!
						</h1>
						<p className="mt-2 text-sm text-stone-500">
							Your DroidClaw license has been successfully activated. You can
							now use all features.
						</p>
						<button
							onClick={() => navigate({ to: '/dashboard' })}
							className="mt-6 rounded-lg bg-stone-900 px-6 py-2.5 text-sm font-medium text-white hover:bg-stone-800"
						>
							Go to dashboard
						</button>
					</div>
				) : (
					<>
						<div className="text-center">
							<div className="mx-auto flex h-14 w-14 items-center justify-center rounded-xl bg-violet-50">
								<KeyRound className="h-7 w-7 text-violet-600" />
							</div>
							<h1 className="mt-4 text-xl font-bold text-stone-900">
								Activate your license
							</h1>
							<p className="mt-2 text-sm text-stone-500">
								Enter your license key to unlock DroidClaw
							</p>
						</div>

						{error && (
							<div className="flex items-start gap-3 rounded-lg bg-red-50 p-3">
								<AlertCircle className="mt-0.5 h-4 w-4 text-red-500" />
								<p className="text-sm text-red-600">
									{error instanceof Error
										? error.message
										: 'Activation failed. Please check your key and try again.'}
								</p>
							</div>
						)}

						{activateCheckout.isPending && (
							<div className="flex items-center justify-center gap-3 py-4">
								<div className="h-5 w-5 animate-spin rounded-full border-2 border-stone-200 border-t-stone-600" />
								<span className="text-sm text-stone-500">
									Activating from checkout...
								</span>
							</div>
						)}

						{!search.checkout_id && (
							<div className="space-y-4">
								<div>
									<label className="block text-sm font-medium text-stone-700">
										License key
									</label>
									<input
										type="text"
										value={licenseKey}
										onChange={(e) => setLicenseKey(e.target.value)}
										placeholder="XXXX-XXXX-XXXX-XXXX"
										className="mt-1 block w-full rounded-lg border border-stone-300 px-3 py-2.5 text-center font-mono text-sm tracking-wider focus:border-violet-500 focus:ring-violet-500"
										onKeyDown={(e) => {
											if (e.key === 'Enter' && licenseKey.trim()) {
												activateKey.mutate();
											}
										}}
									/>
								</div>

								<button
									onClick={() => {
										if (licenseKey.trim()) activateKey.mutate();
									}}
									disabled={!licenseKey.trim() || activateKey.isPending}
									className="flex w-full justify-center rounded-lg bg-stone-900 px-4 py-2.5 text-sm font-medium text-white hover:bg-stone-800 disabled:opacity-50"
								>
									{activateKey.isPending
										? 'Activating...'
										: 'Activate license'}
								</button>
							</div>
						)}

						<div className="border-t border-stone-100 pt-4 text-center">
							<p className="text-xs text-stone-500">
								Don&apos;t have a license?{' '}
								<a
									href="https://droidclaw.com/pricing"
									target="_blank"
									rel="noopener noreferrer"
									onClick={() => track(LICENSE_PURCHASE_CLICK)}
									className="font-medium text-violet-600 hover:text-violet-700"
								>
									Purchase one
								</a>
							</p>
						</div>
					</>
				)}
			</div>
		</div>
	);
}

// web/src/routes/dashboard/activate/+page.svelte
<script lang="ts">
	import { activateLicense, activateFromCheckout } from '$lib/api/license.remote';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { onMount } from 'svelte';
	import Icon from '@iconify/svelte';
	import { LICENSE_ACTIVATE_CHECKOUT, LICENSE_ACTIVATE_MANUAL, LICENSE_PURCHASE_CLICK } from '$lib/analytics/events';
	import * as Card from '$lib/components/ui/card';
	import * as Alert from '$lib/components/ui/alert';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Spinner } from '$lib/components/ui/spinner';

	const checkoutId = page.url.searchParams.get('checkout_id');

	let showKeyInput = $state(false);
	let checkoutStatus = $state<'activating' | 'error' | 'idle'>('idle');
	let checkoutError = $state('');
	let submitting = $state(false);

	async function activateCheckout() {
		if (!checkoutId) return;
		checkoutStatus = 'activating';
		checkoutError = '';
		try {
			await activateFromCheckout({ checkoutId });
			goto('/dashboard');
		} catch (e: any) {
			checkoutError = e.message ?? 'Failed to activate from checkout';
			checkoutStatus = 'error';
		}
	}

	onMount(() => {
		if (checkoutId) activateCheckout();
	});
</script>

<div class="flex min-h-[60vh] items-center justify-center">
{#if checkoutId}
	<!-- Auto-activate from Polar checkout -->
	<Card.Root class="w-full max-w-md shadow-lg border-stone-200/50">
		<Card.Header class="items-center text-center">
			{#if checkoutStatus === 'activating'}
				<div class="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-xl bg-stone-100">
					<Spinner class="h-6 w-6 text-stone-600" />
				</div>
				<Card.Title class="text-2xl">Activating your license...</Card.Title>
				<Card.Description>
					We're setting up your account. This will only take a moment.
				</Card.Description>
			{:else if checkoutStatus === 'error'}
				<div class="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-xl bg-red-50">
					<Icon icon="ph:warning-duotone" class="h-6 w-6 text-red-500" />
				</div>
				<Card.Title class="text-2xl">Activation failed</Card.Title>
				<Card.Description>{checkoutError}</Card.Description>
			{/if}
		</Card.Header>

		<Card.Content class="space-y-4">
			{#if checkoutStatus === 'error'}
				<Button
					onclick={activateCheckout}
					data-umami-event={LICENSE_ACTIVATE_CHECKOUT}
					class="w-full gap-2"
				>
					<Icon icon="ph:arrow-clockwise-duotone" class="h-4 w-4" />
					Retry
				</Button>
			{/if}

			<Alert.Root class="border-stone-200 bg-stone-50">
				<Icon icon="solar:info-circle-bold-duotone" class="h-5 w-5 text-stone-400" />
				<Alert.Description class="text-stone-500">
					If activation doesn't work automatically, check your email for the license key and enter it manually below.
				</Alert.Description>
			</Alert.Root>

			<div class="text-center">
				<p class="text-sm font-medium text-stone-400">Or activate manually</p>
			</div>

			<form
				{...activateLicense.enhance(async ({ submit }) => {
					submitting = true;
					try {
						await submit();
						goto('/dashboard');
					} finally {
						submitting = false;
					}
				})}
				class="space-y-4"
			>
				<div class="space-y-2">
					<Label for="key" class="flex items-center gap-1.5">
						<Icon icon="ph:key-duotone" class="h-4 w-4 text-stone-400" />
						License Key
					</Label>
					<Input
						{...activateLicense.fields.key.as('text')}
						id="key"
						placeholder="DROIDCLAW-XXXX-XXXX-XXXX"
					/>
					{#each activateLicense.fields.key.issues() ?? [] as issue (issue.message)}
						<p class="text-sm text-red-600">{issue.message}</p>
					{/each}
				</div>

				<Button type="submit" class="w-full gap-2" disabled={submitting} data-umami-event={LICENSE_ACTIVATE_MANUAL}>
					{#if submitting}
						<Spinner class="h-4 w-4" />
					{:else}
						<Icon icon="ph:seal-check-duotone" class="h-4 w-4" />
					{/if}
					Activate
				</Button>
			</form>
		</Card.Content>
	</Card.Root>
{:else}
	<!-- Purchase-first flow -->
	<Card.Root class="w-full max-w-md shadow-lg border-stone-200/50">
		<Card.Header class="items-center text-center">
			<Card.Title class="text-2xl">Get started with DroidClaw</Card.Title>
			<Card.Description>Unlock AI-powered Android device control.</Card.Description>
		</Card.Header>

		<Card.Content class="space-y-4">
			<Button
				href="https://buy.polar.sh/polar_cl_jCKKpL4dSdvLZr9H6JYeeCiXjTH98Rf9b4kKM2VqvG2"
				data-umami-event={LICENSE_PURCHASE_CLICK}
				class="w-full gap-2 text-base"
			>
				<Icon icon="ph:credit-card-duotone" class="h-5 w-5" />
				Purchase Now
			</Button>

			<div class="pt-4">
				<button
					type="button"
					onclick={() => showKeyInput = !showKeyInput}
					class="flex w-full items-center justify-center gap-1.5 text-sm text-stone-400 hover:text-stone-600"
				>
					Already have a license key?
					<Icon
						icon="ph:caret-down"
						class="h-3.5 w-3.5 transition-transform {showKeyInput ? 'rotate-180' : ''}"
					/>
				</button>

				{#if showKeyInput}
					<div class="mt-4">
						<form
							{...activateLicense.enhance(async ({ submit }) => {
								submitting = true;
								try {
									await submit();
									goto('/dashboard');
								} finally {
									submitting = false;
								}
							})}
							class="space-y-4"
						>
							<div class="space-y-2">
								<Label for="key-manual" class="flex items-center gap-1.5">
									<Icon icon="ph:key-duotone" class="h-4 w-4 text-stone-400" />
									License Key
								</Label>
								<Input
									{...activateLicense.fields.key.as('text')}
									id="key-manual"
									placeholder="DROIDCLAW-XXXX-XXXX-XXXX"
								/>
								{#each activateLicense.fields.key.issues() ?? [] as issue (issue.message)}
									<p class="text-sm text-red-600">{issue.message}</p>
								{/each}
							</div>

							<Button type="submit" variant="outline" class="w-full gap-2" disabled={submitting} data-umami-event={LICENSE_ACTIVATE_MANUAL}>
								{#if submitting}
									<Spinner class="h-4 w-4" />
								{:else}
									<Icon icon="ph:seal-check-duotone" class="h-4 w-4" />
								{/if}
								Activate
							</Button>
						</form>
					</div>
				{/if}
			</div>
		</Card.Content>
	</Card.Root>
{/if}
</div>
